/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SRINIVAS' at '8/29/16 9:22 PM' with Gradle 3.0
 *
 * @author SRINIVAS, @date 8/29/16 9:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
